#!/bin/bash

# This file is equivalent to the CI workflow that runs on GitHub.
#
# It can be used to fully compile XC16++ locally (it will take really long),
# but can also be used as a guidance on how to build specific XC16++ variants.
#
# The real CI GitHub workflow can be found in .github/workflows/.

cd "$(dirname "$0")"
set -ex

# Build docker containers with the necessary compilation environment
# If you don't need to build for all platforms, you can skip the non-
# relevant ones.
./prepare-container.sh linux-build
./prepare-container.sh windows-build
./prepare-container.sh osx-build
./prepare-container.sh linux-test-compile
./prepare-container.sh windows-test-compile
./prepare-container.sh osx-test-compile
./prepare-container.sh all-test-validate

# Build all XC16++ variants
#
# Again, you can skip the non-relevant versions and OS.
#
# Note: The target version must always be the first argument; the other
# arguments can be omitted or specified in any order depending on the
# desired target operating system(s).
./build-in-container.sh v1.00 linux windows osx
./build-in-container.sh v1.10 linux windows osx
./build-in-container.sh v1.11 linux windows osx
./build-in-container.sh v1.20 linux windows osx
./build-in-container.sh v1.21 linux windows osx
./build-in-container.sh v1.22 linux windows osx
./build-in-container.sh v1.23 linux windows osx
./build-in-container.sh v1.24 linux windows osx
./build-in-container.sh v1.25 linux windows osx
./build-in-container.sh v1.26 linux windows osx
./build-in-container.sh v1.30 linux windows osx
./build-in-container.sh v1.31 linux windows osx
./build-in-container.sh v1.32 linux windows osx
./build-in-container.sh v1.33 linux windows osx
./build-in-container.sh v1.34 linux windows osx
./build-in-container.sh v1.35 linux windows osx
./build-in-container.sh v1.36 linux windows osx
./build-in-container.sh v1.40 linux windows osx
./build-in-container.sh v1.41 linux windows osx
./build-in-container.sh v1.49 linux windows osx
./build-in-container.sh v1.50 linux windows osx
./build-in-container.sh v1.59 linux windows osx
./build-in-container.sh v1.60 linux windows osx
./build-in-container.sh v1.61 linux windows osx
./build-in-container.sh v1.70 linux windows osx
./build-in-container.sh v2.00 linux windows osx
./build-in-container.sh v2.09 linux windows osx
./build-in-container.sh v2.10 linux windows osx

# Compile the tests using the newly-built compilers.
#
# Within the *-test-compile containers, Linux binaries are executed natively,
# Windows binaries are executed in WINE, and OSX binaries are executed through
# maloader.
#
# Note: xc16-vN.NN-OS.tar.xz archives must be present in advance! Install XC16
# and use the pack-xc16-binaries.sh tool to create them.
#
# Note 2: v1.49, v1.59, v1.09 are "Functional Safety" releases whose XC16
# executables will not run without a specific license.
./test-compile-in-container.sh v1.00 linux windows osx
./test-compile-in-container.sh v1.10 linux windows osx
./test-compile-in-container.sh v1.11 linux windows osx
./test-compile-in-container.sh v1.20 linux windows osx
./test-compile-in-container.sh v1.21 linux windows osx
./test-compile-in-container.sh v1.22 linux windows osx
./test-compile-in-container.sh v1.23 linux windows osx
./test-compile-in-container.sh v1.24 linux windows osx
./test-compile-in-container.sh v1.25 linux windows osx
./test-compile-in-container.sh v1.26 linux windows osx
./test-compile-in-container.sh v1.30 linux windows osx
./test-compile-in-container.sh v1.31 linux windows osx
./test-compile-in-container.sh v1.32 linux windows osx
./test-compile-in-container.sh v1.33 linux windows osx
./test-compile-in-container.sh v1.34 linux windows osx
./test-compile-in-container.sh v1.35 linux windows osx
./test-compile-in-container.sh v1.36 linux windows osx
./test-compile-in-container.sh v1.40 linux windows osx
./test-compile-in-container.sh v1.41 linux windows osx
#./test-compile-in-container.sh v1.49 linux windows osx
./test-compile-in-container.sh v1.50 linux windows osx
#./test-compile-in-container.sh v1.59 linux windows osx
./test-compile-in-container.sh v1.60 linux windows osx
./test-compile-in-container.sh v1.61 linux windows osx
./test-compile-in-container.sh v1.70 linux windows osx
./test-compile-in-container.sh v2.00 linux windows osx
#./test-compile-in-container.sh v2.09 linux windows osx
./test-compile-in-container.sh v2.10 linux windows osx

# Validate tests
#
# The script takes a list of test bundles (generated by the
# test-compile-in-container.sh) script.
./test-validate-in-container.sh test-report.zip build-*/test-bundle-*.zip
